Fix application ID value in AndroidManifest.xml
Numerics are converted to numbers otherwise

  Key com.meta.wearable.mwdat.APPLICATION_ID expected String but value was a java.lang.Integer.  The default value <null> was returned.
19:29:23.142 Bundle            W  Attempt to cast generated internal exception:
                                  java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String